# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.x"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-cov
        pip install flake8-html
        pip install autopep8
        pip install pyflakes
        pip install pylint
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test random file with autopep8
      run: 
          autopep8 rand.py
    - name: Test sort file with autopep8
      run:
          autopep8 hw2_debugging.py
    - name: Test with pyflake
      run: |
        pyflakes hw2_debugging.py rand.py
    - name: Test with pylint
      run:
        pylint hw2_debugging.py rand.py  
    - name: Generate pylint badge
    - uses: Silleellie/pylint-github-action@v2
      with:
          lint-path: |
            hw2_debugging.py
            rand.py
          python-version: 3.13  
    - name: Test with pytest
      run: |
        pytest tests.py --doctest-modules --junitxml=junit/test-results.xml --cov --cov-report=xml --cov-report=html
    - name: Upload results to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        
